name: Ubuntu REMOTE DESKTOP PROTOCOL

on:
  workflow_dispatch:

jobs:
  ubuntu-kde-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install KDE Plasma & XRDP
        run: |
          sudo apt update
          sudo apt install -y kde-standard xrdp
          echo "startplasma-x11" > ~/.xsession
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: Create RDP User with Full Sudo Access
        run: |
          sudo useradd -m -s /bin/bash ubuntu || true
          echo "ubuntu:1234" | sudo chpasswd
          sudo usermod -aG sudo ubuntu
          echo "ubuntu ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ubuntu

      - name: Install & Start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=ubuntu-kde-${{ github.run_id }}
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: Show RDP Access Info
        run: |
          echo ""
          echo "=== RDP ACCESS ==="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Username: ubuntu"
          echo "Password: 1234"
          echo "=================="
          echo ""

      - name: Keep Session Alive
        run: |
          while true; do
            echo "Ubuntu KDE RDP running at $(date)"
            sleep 300
          done
