name: Ubuntu SSH via Tailscale

on:
  workflow_dispatch:

jobs:
  ubuntu-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install SSH and Create User
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

          sudo useradd -m -s /bin/bash ubuntu || true
          echo "ubuntu:1234" | sudo chpasswd
          sudo usermod -aG sudo ubuntu
          echo "ubuntu ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ubuntu

      - name: Install & Start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=ubuntu-ssh-${{ github.run_id }}
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: Show SSH Access Info
        run: |
          echo ""
          echo "=== SSH ACCESS ==="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Username: ubuntu"
          echo "Password: 1234"
          echo "=================="
          echo ""

      - name: Keep Session Alive
        run: |
          while true; do
            echo "Ubuntu SSH session running at $(date)"
            sleep 300
          done
